"use client";

import { useMemo, useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Check,
  Eye,
  GitBranch,
  Pencil,
  Plus,
  Search,
  ShieldCheck,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  UserPlus,
} from "lucide-react";
import { api } from "@/lib/api";
import type { ChangeApproval, ChangeRecord, UserOut } from "@/lib/types";
import { cn, formatTimeAgo, priorityColor } from "@/lib/utils";
import { Alert, Button, ConfirmDialog, DataListCard, DataTable, DataTableViewport, Dialog, EmptyState, ErrorState, IconButton, ListText, Skeleton } from "@/components/ui";
import { PageFrame, PageHeader, SummaryStrip } from "@/components/layout/PageLayout";

const STATUSES = ["", "Draft", "Submitted", "Approved", "In Progress", "Completed", "Rejected", "Cancelled"];
const TYPES = ["Normal", "Standard", "Emergency"];
const RISKS = ["Low", "Medium", "High"];
const PRIORITIES = ["P1", "P2", "P3", "P4"];

const STATUS_STYLES: Record<string, string> = {
  Draft: "border-linen-500 bg-linen-300 text-ink-600",
  Submitted: "border-clay-400/40 bg-clay-400/10 text-clay-700",
  Approved: "border-moss-500/30 bg-moss-500/10 text-moss-700",
  "In Progress": "border-clay-400/30 bg-clay-400/10 text-clay-700",
  Completed: "border-moss-500/40 bg-moss-500/15 text-moss-700",
  Rejected: "border-rust-400/30 bg-rust-400/10 text-rust-600",
  Cancelled: "border-linen-500 bg-linen-300 text-ink-500",
};
const RISK_STYLES: Record<string, string> = {
  Low: "border-moss-500/30 bg-moss-500/10 text-moss-700",
  Medium: "border-amber-400/40 bg-amber-400/10 text-amber-700",
  High: "border-rust-400/30 bg-rust-400/10 text-rust-600",
};
const TYPE_STYLES: Record<string, string> = {
  Normal: "border-clay-400/30 bg-clay-400/10 text-clay-700",
  Standard: "border-moss-500/30 bg-moss-500/10 text-moss-700",
  Emergency: "border-rust-400/30 bg-rust-400/10 text-rust-600",
};

function errorMessage(error: unknown) { return error instanceof Error ? error.message : error ? String(error) : "An unexpected error occurred."; }
function formatDate(value: string | null) { if (!value) return "Not scheduled"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "Invalid date" : date.toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }); }
function Pill({ value, styles }: { value: string; styles: Record<string, string> }) { return <span className={cn("inline-flex whitespace-nowrap rounded-full border px-2.5 py-1 text-[11px] font-semibold", styles[value] ?? "border-linen-500 bg-linen-300 text-ink-600")}>{value}</span>; }

export default function ChangesPage() {
  const queryClient = useQueryClient();
  const [statusFilter, setStatusFilter] = useState("");
  const [search, setSearch] = useState("");
  const [formChange, setFormChange] = useState<ChangeRecord | null | undefined>(undefined);
  const [viewing, setViewing] = useState<ChangeRecord | null>(null);
  const [deleting, setDeleting] = useState<ChangeRecord | null>(null);

  const changesQuery = useQuery({ queryKey: ["changes", statusFilter], queryFn: () => api.getChanges(statusFilter || undefined) });
  const usersQuery = useQuery({ queryKey: ["users"], queryFn: api.getUsers });
  const createMutation = useMutation({ mutationFn: (payload: Partial<ChangeRecord>) => api.createChange(payload), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["changes"] }); setFormChange(undefined); } });
  const updateMutation = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: Partial<ChangeRecord> }) => api.updateChange(id, payload), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["changes"] }); setFormChange(undefined); } });
  const deleteMutation = useMutation({ mutationFn: (id: string) => api.deleteChange(id), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["changes"] }); setDeleting(null); }, onError: () => setDeleting(null) });

  const changes = useMemo(() => changesQuery.data ?? [], [changesQuery.data]);
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); if (!term) return changes; return changes.filter((change) => [change.title, change.description, change.change_type, change.assigned_name].filter(Boolean).some((value) => String(value).toLowerCase().includes(term))); }, [changes, search]);
  const pendingReview = changes.filter((item) => item.status === "Submitted").length;
  const inProgress = changes.filter((item) => item.status === "In Progress").length;
  const highRisk = changes.filter((item) => item.risk_level === "High" && !["Completed", "Cancelled"].includes(item.status)).length;
  const resetFormErrors = () => { createMutation.reset(); updateMutation.reset(); };

  return <PageFrame width="wide" className="pb-10">
    <PageHeader eyebrow="Release governance" icon={<GitBranch className="h-4 w-4" />} title="Changes" description="Plan operational changes, document risk and rollback readiness, and capture accountable approvals." actions={<Button leadingIcon={<Plus className="h-4 w-4" />} onClick={() => { resetFormErrors(); setFormChange(null); }}>New change</Button>} />

    {(pendingReview > 0 || inProgress > 0 || highRisk > 0) && <SummaryStrip label="Change overview" className="xl:grid-cols-3">{[{ label: "Awaiting review", value: pendingReview, note: "Submitted for approval" }, { label: "In progress", value: inProgress, note: "Execution underway" }, { label: "High risk", value: highRisk, note: "Active records needing attention" }].filter((metric) => metric.value > 0).map((metric) => <div key={metric.label} className="rounded-2xl border border-linen-400 bg-linen-50 p-4 shadow-[var(--shadow-card)]"><p className="text-xs font-medium text-ink-500">{metric.label}</p><p className="mt-2 text-2xl font-semibold tabular-nums tracking-tight text-ink-800">{metric.value}</p><p className="mt-1 text-xs text-ink-400">{metric.note}</p></div>)}</SummaryStrip>}

    <section className="overflow-hidden rounded-2xl border border-linen-400 bg-linen-50 shadow-[var(--shadow-card)]">
      <div className="flex flex-col gap-3 border-b border-linen-400 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-ink-800">Change register</h2><p className="mt-0.5 text-xs text-ink-500">{filtered.length} {filtered.length === 1 ? "record" : "records"} shown</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><span className="sr-only">Search changes</span><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-400" aria-hidden="true" /><input type="search" className="input-base min-h-10 pl-9 sm:w-64" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title, type, owner…" /></label><label><span className="sr-only">Filter by status</span><select className="input-base min-h-10 sm:w-52" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}>{STATUSES.map((status) => <option key={status || "all"} value={status}>{status || "All statuses"}</option>)}</select></label></div></div>
      {deleteMutation.error && <div className="p-4 pb-0"><Alert variant="danger" title="Change was not deleted">{errorMessage(deleteMutation.error)}</Alert></div>}
      {changesQuery.isLoading ? <RegisterSkeleton /> : changesQuery.isError ? <div className="p-4"><ErrorState title="Changes could not be loaded" description={errorMessage(changesQuery.error)} onRetry={() => changesQuery.refetch()} retrying={changesQuery.isFetching} /></div> : !filtered.length ? <div className="p-4"><EmptyState icon={<GitBranch className="h-5 w-5" />} title={changes.length ? "No matching changes" : "No changes recorded"} description={changes.length ? "Adjust the search or status filter to broaden this view." : "Create a governed change record before modifying a production service."} action={!changes.length ? <Button leadingIcon={<Plus className="h-4 w-4" />} onClick={() => setFormChange(null)}>Create first change</Button> : <Button variant="secondary" onClick={() => { setSearch(""); setStatusFilter(""); }}>Clear filters</Button>} /></div> : <><DataTableViewport label="Change register" className="hidden md:block"><DataTable className="min-w-[760px]"><colgroup><col className="w-[34%]" /><col className="w-[22%]" /><col className="w-[16%]" /><col className="w-[18%]" /><col className="w-[10%]" /></colgroup><thead className="border-b border-linen-400 bg-linen-100 text-[11px] font-semibold uppercase tracking-[0.12em] text-ink-500"><tr><th className="px-5 py-3">Change</th><th className="px-4 py-3">Classification</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Schedule</th><th className="px-5 py-3 text-right"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-linen-300">{filtered.map((change) => <ChangeRow key={change.id} change={change} onView={() => setViewing(change)} onEdit={() => { resetFormErrors(); setFormChange(change); }} onDelete={() => { deleteMutation.reset(); setDeleting(change); }} />)}</tbody></DataTable></DataTableViewport><div className="grid gap-3 bg-linen-100/60 p-3 md:hidden">{filtered.map((change) => <ChangeCard key={change.id} change={change} onView={() => setViewing(change)} onEdit={() => { resetFormErrors(); setFormChange(change); }} onDelete={() => { deleteMutation.reset(); setDeleting(change); }} />)}</div></>}
    </section>

    <ChangeFormDialog key={formChange?.id ?? (formChange === null ? "new" : "closed")} open={formChange !== undefined} change={formChange ?? null} users={usersQuery.data ?? []} usersUnavailable={usersQuery.isError} onOpenChange={(open) => { if (!open && !createMutation.isPending && !updateMutation.isPending) setFormChange(undefined); }} onSubmit={(payload) => formChange ? updateMutation.mutate({ id: formChange.id, payload }) : createMutation.mutate(payload)} pending={createMutation.isPending || updateMutation.isPending} error={createMutation.error || updateMutation.error} />
    <ChangeDetailDialog change={viewing} users={usersQuery.data ?? []} usersUnavailable={usersQuery.isError} onOpenChange={(open) => { if (!open) setViewing(null); }} />
    <ConfirmDialog open={Boolean(deleting)} onOpenChange={(open) => { if (!open) setDeleting(null); }} title="Delete change record?" description={<>This permanently removes <strong>{deleting?.title}</strong> and its approval history. No deployment action is performed.</>} confirmLabel="Delete change" destructive pending={deleteMutation.isPending} onConfirm={() => { if (deleting) deleteMutation.mutate(deleting.id); }} />
  </PageFrame>;
}

function RegisterSkeleton() { return <div className="space-y-3 p-5" role="status" aria-label="Loading changes"><Skeleton className="h-10 w-full" />{[1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-14 w-full" />)}</div>; }
type ChangeActions = { change: ChangeRecord; onView: () => void; onEdit: () => void; onDelete: () => void };
function ChangeRow({ change, onView, onEdit, onDelete }: ChangeActions) { return <tr className="transition-colors hover:bg-linen-100/80"><td className="px-5 py-4"><button onClick={onView} className="block w-full min-w-0 text-left focus-visible:rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]"><ListText text={change.title} lines={2} className="font-semibold leading-5 text-ink-800" /><span className="mt-1 block font-mono text-[11px] text-ink-400">{change.id.slice(0, 8).toUpperCase()}</span></button></td><td className="px-4 py-4"><Pill value={change.change_type} styles={TYPE_STYLES} /><div className="mt-2 flex flex-wrap gap-1.5"><Pill value={change.risk_level} styles={RISK_STYLES} />{change.priority ? <span className={cn("inline-flex whitespace-nowrap rounded-full border px-2.5 py-1 text-[11px] font-semibold", priorityColor(change.priority))}>{change.priority}</span> : null}</div></td><td className="px-4 py-4"><Pill value={change.status} styles={STATUS_STYLES} />{change.assigned_name && <ListText text={change.assigned_name} lines={2} className="mt-2 text-xs text-ink-500" />}</td><td className="px-4 py-4 text-xs text-ink-600"><span className="block font-medium text-ink-600">{formatDate(change.scheduled_start)}</span>{change.scheduled_end && <span className="mt-1 block text-[11px] text-ink-400">Ends {formatDate(change.scheduled_end)}</span>}</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><IconButton size="sm" aria-label={`View ${change.title}`} icon={<Eye className="h-4 w-4" />} onClick={onView} /><IconButton size="sm" aria-label={`Edit ${change.title}`} icon={<Pencil className="h-4 w-4" />} onClick={onEdit} /><IconButton size="sm" aria-label={`Delete ${change.title}`} icon={<Trash2 className="h-4 w-4" />} onClick={onDelete} className="text-rust-600 hover:bg-rust-400/10" /></div></td></tr>; }
function ChangeCard({ change, onView, onEdit, onDelete }: ChangeActions) { return <DataListCard><div className="flex min-w-0 items-start justify-between gap-3"><button onClick={onView} className="min-w-0 flex-1 text-left"><ListText text={change.title} lines={2} className="font-semibold leading-5 text-ink-800" /><span className="mt-1 block font-mono text-[11px] text-ink-400">{change.id.slice(0, 8).toUpperCase()}</span></button><Pill value={change.risk_level} styles={RISK_STYLES} /></div><div className="mt-4 flex flex-wrap gap-2"><Pill value={change.status} styles={STATUS_STYLES} /><Pill value={change.change_type} styles={TYPE_STYLES} />{change.priority ? <span className={cn("inline-flex whitespace-nowrap rounded-full border px-2.5 py-1 text-[11px] font-semibold", priorityColor(change.priority))}>{change.priority}</span> : null}</div><div className="mt-4 flex min-w-0 flex-col gap-3 border-t border-linen-300 pt-3 xs:flex-row xs:items-center xs:justify-between"><span className="min-w-0 text-xs text-ink-500">{formatDate(change.scheduled_start)}</span><div className="flex shrink-0 gap-1 self-end xs:self-auto"><IconButton size="sm" aria-label={`View ${change.title}`} icon={<Eye className="h-4 w-4" />} onClick={onView} /><IconButton size="sm" aria-label={`Edit ${change.title}`} icon={<Pencil className="h-4 w-4" />} onClick={onEdit} /><IconButton size="sm" aria-label={`Delete ${change.title}`} icon={<Trash2 className="h-4 w-4" />} onClick={onDelete} className="text-rust-600" /></div></div></DataListCard>; }

function ChangeFormDialog({ open, change, users, usersUnavailable, onOpenChange, onSubmit, pending, error }: { open: boolean; change: ChangeRecord | null; users: UserOut[]; usersUnavailable: boolean; onOpenChange: (open: boolean) => void; onSubmit: (payload: Partial<ChangeRecord>) => void; pending: boolean; error: unknown }) {
  const [title, setTitle] = useState(change?.title ?? ""); const [description, setDescription] = useState(change?.description ?? ""); const [type, setType] = useState(change?.change_type ?? "Normal"); const [status, setStatus] = useState(change?.status ?? "Draft"); const [priority, setPriority] = useState(change?.priority ?? ""); const [risk, setRisk] = useState(change?.risk_level ?? "Low"); const [impact, setImpact] = useState(change?.impact ?? ""); const [rollback, setRollback] = useState(change?.rollback_plan ?? ""); const [testPlan, setTestPlan] = useState(change?.test_plan ?? ""); const [start, setStart] = useState(change?.scheduled_start?.slice(0, 16) ?? ""); const [end, setEnd] = useState(change?.scheduled_end?.slice(0, 16) ?? ""); const [assignedTo, setAssignedTo] = useState(change?.assigned_to ?? "");
  const invalidWindow = Boolean(start && end && new Date(end) <= new Date(start));
  return <Dialog open={open} onOpenChange={onOpenChange} title={change ? "Edit change" : "Create change"} description="Document scope, controls, ownership, and execution timing before review." dismissible={!pending} className="max-w-3xl" footer={<><Button variant="secondary" disabled={pending} onClick={() => onOpenChange(false)}>Cancel</Button><Button pending={pending} pendingLabel={change ? "Saving…" : "Creating…"} disabled={!title.trim() || invalidWindow} onClick={() => onSubmit({ title: title.trim(), description: description.trim(), change_type: type, status, priority, risk_level: risk, impact: impact.trim() || null, rollback_plan: rollback.trim() || null, test_plan: testPlan.trim() || null, scheduled_start: start ? new Date(start).toISOString() : null, scheduled_end: end ? new Date(end).toISOString() : null, assigned_to: assignedTo || null })}>{change ? "Save changes" : "Create change"}</Button></>}>
    <div className="space-y-5">{Boolean(error) && <Alert variant="danger" title={change ? "Changes were not saved" : "Change was not created"}>{errorMessage(error)}</Alert>}{usersUnavailable && <Alert variant="warning" title="Assignees unavailable">The user directory could not be loaded. You can save this change without an assignee.</Alert>}<Field label="Title" required><input autoFocus className="input-base" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="What will change?" /></Field><Field label="Description"><textarea className="input-base min-h-24 resize-y" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Purpose, scope, dependencies, and expected outcome" /></Field>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Status"><select className="input-base" value={status} onChange={(event) => setStatus(event.target.value)}>{STATUSES.filter(Boolean).map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Change type"><select className="input-base" value={type} onChange={(event) => setType(event.target.value)}>{TYPES.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Risk"><select className="input-base" value={risk} onChange={(event) => setRisk(event.target.value)}>{RISKS.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Priority"><select className="input-base" value={priority} onChange={(event) => setPriority(event.target.value)}><option value="">Not set</option>{PRIORITIES.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Assignee"><select className="input-base" value={assignedTo} onChange={(event) => setAssignedTo(event.target.value)} disabled={usersUnavailable}><option value="">Unassigned</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></Field></div>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Scheduled start"><input type="datetime-local" className="input-base" value={start} onChange={(event) => setStart(event.target.value)} /></Field><Field label="Scheduled end"><input type="datetime-local" className="input-base" value={end} min={start || undefined} onChange={(event) => setEnd(event.target.value)} aria-invalid={invalidWindow} /></Field></div>{invalidWindow && <Alert variant="danger" title="Invalid schedule">The end time must be later than the start time.</Alert>}
      <Field label="Impact"><textarea className="input-base min-h-20 resize-y" value={impact} onChange={(event) => setImpact(event.target.value)} placeholder="Customer, service, security, and operational impact" /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Rollback plan"><textarea className="input-base min-h-28 resize-y" value={rollback} onChange={(event) => setRollback(event.target.value)} placeholder="Trigger, steps, owner, and recovery validation" /></Field><Field label="Test plan"><textarea className="input-base min-h-28 resize-y" value={testPlan} onChange={(event) => setTestPlan(event.target.value)} placeholder="Pre-change checks and success criteria" /></Field></div>
    </div>
  </Dialog>;
}

function ChangeDetailDialog({ change, users, usersUnavailable, onOpenChange }: { change: ChangeRecord | null; users: UserOut[]; usersUnavailable: boolean; onOpenChange: (open: boolean) => void }) {
  const queryClient = useQueryClient(); const [approverId, setApproverId] = useState(""); const [decision, setDecision] = useState<{ approval: ChangeApproval; value: "approved" | "rejected" } | null>(null);
  const detailQuery = useQuery({ queryKey: ["change", change?.id], queryFn: () => api.getChange(change!.id), enabled: Boolean(change), initialData: change ?? undefined });
  const approvalsQuery = useQuery({ queryKey: ["change-approvals", change?.id], queryFn: () => api.getChangeApprovals(change!.id), enabled: Boolean(change) });
  const addMutation = useMutation({ mutationFn: (id: string) => api.addChangeApproval(change!.id, id), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["change-approvals", change?.id] }); setApproverId(""); } });
  const decideMutation = useMutation({ mutationFn: ({ approverId: id, value }: { approverId: string; value: "approved" | "rejected" }) => api.decideApproval(change!.id, id, value), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["change-approvals", change?.id] }); setDecision(null); }, onError: () => setDecision(null) });
  const current = detailQuery.data ?? change;
  return <><Dialog open={Boolean(change) && !decision} onOpenChange={onOpenChange} title={current?.title ?? "Change details"} description={current ? `Change ${current.id.slice(0, 8).toUpperCase()}` : undefined} className="max-w-3xl">{current && <div className="space-y-6">{detailQuery.isError && <Alert variant="warning" title="Latest record unavailable">Showing the last loaded data. {errorMessage(detailQuery.error)}</Alert>}<div className="flex flex-wrap gap-2"><Pill value={current.status} styles={STATUS_STYLES} /><Pill value={current.change_type} styles={TYPE_STYLES} /><Pill value={current.risk_level} styles={RISK_STYLES} />{current.priority && <span className={cn("inline-flex rounded-full border px-2.5 py-1 text-[11px] font-semibold", priorityColor(current.priority))}>{current.priority}</span>}</div>
      <dl className="grid gap-4 rounded-xl border border-linen-400 bg-linen-100 p-4 sm:grid-cols-2"><Detail label="Assignee" value={current.assigned_name || "Unassigned"} /><Detail label="Requester" value={current.requested_name || "Unknown"} /><Detail label="Start" value={formatDate(current.scheduled_start)} /><Detail label="End" value={formatDate(current.scheduled_end)} /></dl><Narrative label="Description" value={current.description} /><Narrative label="Impact" value={current.impact} /><div className="grid gap-4 sm:grid-cols-2"><NarrativeCard label="Rollback plan" value={current.rollback_plan} /><NarrativeCard label="Test plan" value={current.test_plan} /></div>
      <section className="border-t border-linen-400 pt-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h3 className="text-sm font-semibold text-ink-800">Approvals</h3><p className="mt-1 text-xs text-ink-500">Named decisions create an accountable review trail.</p></div><div className="flex gap-2"><label className="min-w-0 flex-1 sm:w-56"><span className="sr-only">Select approver</span><select className="input-base min-h-10" value={approverId} onChange={(event) => setApproverId(event.target.value)} disabled={usersUnavailable}><option value="">Select approver</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><Button size="sm" leadingIcon={<UserPlus className="h-4 w-4" />} pending={addMutation.isPending} pendingLabel="Adding…" disabled={!approverId || usersUnavailable} onClick={() => addMutation.mutate(approverId)}>Add</Button></div></div>
        {usersUnavailable && <Alert className="mt-4" variant="warning" title="Approver directory unavailable">Existing decisions remain visible, but new approvers cannot be added.</Alert>}{addMutation.error && <Alert className="mt-4" variant="danger" title="Approver was not added">{errorMessage(addMutation.error)}</Alert>}{decideMutation.error && <Alert className="mt-4" variant="danger" title="Decision was not recorded">{errorMessage(decideMutation.error)}</Alert>}
        <div className="mt-4">{approvalsQuery.isLoading ? <div className="space-y-2"><Skeleton className="h-14" /><Skeleton className="h-14" /></div> : approvalsQuery.isError ? <ErrorState className="min-h-40" title="Approvals could not be loaded" description={errorMessage(approvalsQuery.error)} onRetry={() => approvalsQuery.refetch()} retrying={approvalsQuery.isFetching} /> : approvalsQuery.data?.length ? <div className="divide-y divide-linen-300 rounded-xl border border-linen-400">{approvalsQuery.data.map((approval) => <ApprovalRow key={approval.id} approval={approval} pending={decideMutation.isPending} onDecision={(value) => { decideMutation.reset(); setDecision({ approval, value }); }} />)}</div> : <EmptyState className="min-h-40" icon={<ShieldCheck className="h-5 w-5" />} title="No approvers assigned" description="Add the first reviewer to begin the approval trail." />}</div>
      </section><div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-ink-400">{current.created_at && <span>Created {formatTimeAgo(current.created_at)}</span>}{current.updated_at && <span>Updated {formatTimeAgo(current.updated_at)}</span>}{current.completed_at && <span>Completed {formatTimeAgo(current.completed_at)}</span>}</div>
    </div>}</Dialog><ConfirmDialog open={Boolean(decision)} onOpenChange={(open) => { if (!open) setDecision(null); }} title={decision?.value === "approved" ? "Approve this change?" : "Reject this change?"} description={<>Record <strong>{decision?.value}</strong> for {decision?.approval.approver_name || "this approver"}. This decision becomes part of the change audit trail.</>} confirmLabel={decision?.value === "approved" ? "Record approval" : "Record rejection"} destructive={decision?.value === "rejected"} pending={decideMutation.isPending} onConfirm={() => { if (decision) decideMutation.mutate({ approverId: decision.approval.approver_id, value: decision.value }); }} /></>;
}

function ApprovalRow({ approval, pending, onDecision }: { approval: ChangeApproval; pending: boolean; onDecision: (value: "approved" | "rejected") => void }) {
  const decided = Boolean(approval.decision);
  return <div className="flex min-w-0 items-start justify-between gap-3 p-3">
    <div className="min-w-0 flex-1">
      <ListText text={approval.approver_name || approval.approver_id} lines={2} className="text-sm font-medium text-ink-700" />
      <div className="mt-1 flex min-w-0 flex-wrap items-center gap-2">
        {decided ? <span className={cn("inline-flex shrink-0 rounded-full border px-2 py-0.5 text-[10px] font-semibold capitalize", approval.decision === "approved" ? "border-moss-500/30 bg-moss-500/10 text-moss-700" : "border-rust-400/30 bg-rust-400/10 text-rust-600")}>{approval.decision}</span> : <span className="shrink-0 text-xs text-ink-400">Pending decision</span>}
        {approval.comment && <ListText text={approval.comment} lines={2} className="min-w-0 text-xs text-ink-500" />}
      </div>
    </div>
    {!decided && <div className="flex shrink-0 gap-1"><IconButton size="sm" aria-label={`Approve for ${approval.approver_name || approval.approver_id}`} icon={<ThumbsUp className="h-4 w-4" />} disabled={pending} onClick={() => onDecision("approved")} className="text-moss-700" /><IconButton size="sm" aria-label={`Reject for ${approval.approver_name || approval.approver_id}`} icon={<ThumbsDown className="h-4 w-4" />} disabled={pending} onClick={() => onDecision("rejected")} className="text-rust-600" /></div>}
  </div>;
}
function Field({ label, required = false, children }: { label: string; required?: boolean; children: ReactNode }) { return <label className="block space-y-1.5"><span className="text-xs font-semibold text-ink-600">{label}{required && <span className="text-rust-600"> *</span>}</span>{children}</label>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-[11px] font-semibold uppercase tracking-wider text-ink-400">{label}</dt><dd className="mt-1 text-sm text-ink-700">{value}</dd></div>; }
function Narrative({ label, value }: { label: string; value: string | null }) { if (!value) return null; return <section><h3 className="text-xs font-semibold uppercase tracking-wider text-ink-400">{label}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-ink-700">{value}</p></section>; }
function NarrativeCard({ label, value }: { label: string; value: string | null }) { return <section className="rounded-xl border border-linen-400 p-4"><h3 className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-ink-500"><Check className="h-3.5 w-3.5" aria-hidden="true" />{label}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-ink-700">{value || "Not documented"}</p></section>; }
