"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-07-12 00:45:19.296105
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Frozen pre-migration contract. An unversioned Tickety database created by
# the former create_all startup path may adopt this baseline only when every
# baseline table and column is present; partial schemas fail closed.
BASELINE_COLUMNS = {
    'assets': ['id', 'name', 'asset_type', 'asset_tag', 'status', 'owner_id', 'location', 'vendor', 'model', 'purchase_date', 'warranty_expiry', 'cost', 'notes', 'created_at', 'updated_at'],
    'change_approvals': ['id', 'change_id', 'approver_id', 'decision', 'comment', 'decided_at', 'created_at'],
    'change_ticket_links': ['id', 'change_id', 'ticket_id'],
    'changes': ['id', 'title', 'description', 'change_type', 'status', 'priority', 'risk_level', 'impact', 'rollback_plan', 'test_plan', 'scheduled_start', 'scheduled_end', 'requested_by', 'assigned_to', 'completed_at', 'created_at', 'updated_at'],
    'kb_articles': ['id', 'title', 'slug', 'content', 'category', 'tags', 'author_id', 'status', 'views', 'helpful', 'not_helpful', 'created_at', 'updated_at'],
    'notification_config': ['id', 'event', 'label', 'enabled', 'channels', 'created_at'],
    'problem_ticket_links': ['id', 'problem_id', 'ticket_id', 'linked_at'],
    'problems': ['id', 'title', 'description', 'status', 'priority', 'category', 'assigned_to', 'root_cause', 'workaround', 'resolution', 'impact_scope', 'closed_at', 'created_at', 'updated_at'],
    'projects': ['id', 'name', 'key', 'description', 'lead_id', 'status', 'created_at', 'updated_at'],
    'recognitions': ['id', 'user_id', 'recognition_key', 'unlocked_at', 'ticket_id'],
    'service_items': ['id', 'name', 'description', 'category', 'pricing', 'sla_hours', 'approval_required', 'is_active', 'created_at', 'updated_at'],
    'service_requests': ['id', 'ticket_id', 'service_item_id', 'quantity', 'justification', 'created_at'],
    'sessions': ['token', 'user_id', 'created_at', 'expires_at', 'ip', 'user_agent'],
    'settings': ['key', 'value', 'updated_at'],
    'survey_responses': ['id', 'survey_id', 'rating', 'comment', 'submitted_at'],
    'survey_templates': ['id', 'name', 'question', 'is_active', 'created_at'],
    'surveys': ['id', 'ticket_id', 'template_id', 'sent_at', 'responded_at', 'created_at'],
    'sync_state': ['id', 'provider', 'last_synced_at', 'last_status', 'last_error', 'total_synced'],
    'ticket_audit_log': ['id', 'ticket_id', 'field', 'old_value', 'new_value', 'changed_by', 'changed_at'],
    'ticket_categories': ['id', 'name', 'description', 'color', 'created_at'],
    'ticket_comments': ['id', 'ticket_id', 'author_id', 'author_name', 'body', 'is_private', 'created_at'],
    'ticket_kb_links': ['id', 'ticket_id', 'kb_article_id', 'created_at', 'created_by'],
    'ticket_priority_config': ['id', 'name', 'label', 'color', 'sla_hours', 'weight', 'sort_order'],
    'ticket_status_config': ['id', 'name', 'label', 'color', 'is_open', 'is_terminal', 'sort_order'],
    'tickets': ['id', 'subject', 'description', 'reporter', 'status', 'priority', 'sentiment', 'category', 'mood', 'complexity', 'ai_reasoning', 'suggested_response', 'external_source', 'external_id', 'external_url', 'external_status', 'external_assignee_id', 'external_updated_at', 'resolved_by', 'resolved_at', 'points_awarded', 'points_awarded_sent', 'created_at', 'updated_at'],
    'time_entries': ['id', 'ticket_id', 'user_id', 'description', 'minutes', 'entry_date', 'created_at'],
    'user_mappings': ['id', 'tickety_user_id', 'external_source', 'external_assignee_id'],
    'users': ['id', 'name', 'email', 'avatar', 'title', 'impact_points', 'tier', 'momentum', 'last_action_at', 'created_at'],
}


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    inspector = sa.inspect(op.get_bind())
    existing_tables = set(inspector.get_table_names()) - {'alembic_version'}
    application_tables = existing_tables.intersection(BASELINE_COLUMNS)
    if application_tables:
        missing_tables = sorted(set(BASELINE_COLUMNS) - existing_tables)
        missing_columns = {
            table: sorted(set(columns) - {c['name'] for c in inspector.get_columns(table)})
            for table, columns in BASELINE_COLUMNS.items()
            if table in existing_tables
        }
        missing_columns = {table: columns for table, columns in missing_columns.items() if columns}
        if missing_tables or missing_columns:
            raise RuntimeError(
                'Unversioned database does not match the Tickety baseline; '
                f'missing tables={missing_tables}, missing columns={missing_columns}'
            )
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('channels', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event')
    )
    op.create_table('service_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('pricing', sa.String(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_items_category'), ['category'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=False)

    op.create_table('survey_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('total_synced', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('ticket_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket_priority_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket_status_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('impact_points', sa.Integer(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('momentum', sa.Integer(), nullable=True),
    sa.Column('last_action_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_tag', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('warranty_expiry', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_tag')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_name'), ['name'], unique=False)

    op.create_table('changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('test_plan', sa.Text(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_changes_title'), ['title'], unique=False)

    op.create_table('kb_articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('helpful', sa.Integer(), nullable=True),
    sa.Column('not_helpful', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('kb_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_articles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_articles_title'), ['title'], unique=False)
        batch_op.create_index('ix_kb_status_cat', ['status', 'category'], unique=False)

    op.create_table('problems',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('workaround', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('impact_scope', sa.String(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_title'), ['title'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lead_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('sessions',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reporter', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('complexity', sa.Integer(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('suggested_response', sa.Text(), nullable=True),
    sa.Column('external_source', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('external_status', sa.String(), nullable=True),
    sa.Column('external_assignee_id', sa.String(), nullable=True),
    sa.Column('external_updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('points_awarded_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_source', 'external_id', name='uix_external_ticket')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_id'), ['id'], unique=False)

    op.create_table('user_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tickety_user_id', sa.String(), nullable=False),
    sa.Column('external_source', sa.String(), nullable=False),
    sa.Column('external_assignee_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tickety_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_source', 'external_assignee_id', name='uix_external_assignee')
    )
    with op.batch_alter_table('user_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_mappings_tickety_user_id'), ['tickety_user_id'], unique=False)

    op.create_table('change_approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_id', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_id', 'approver_id', name='uix_change_approver')
    )
    with op.batch_alter_table('change_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_approvals_change_id'), ['change_id'], unique=False)

    op.create_table('change_ticket_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('change_id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_ticket_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_ticket_links_change_id'), ['change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_ticket_links_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('problem_ticket_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'ticket_id', name='uix_problem_ticket')
    )
    with op.batch_alter_table('problem_ticket_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_ticket_links_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_problem_ticket_links_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('recognitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('recognition_key', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('ticket_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recognition_key', name='uix_user_recognition')
    )
    with op.batch_alter_table('recognitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognitions_user_id'), ['user_id'], unique=False)

    op.create_table('service_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('service_item_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_items.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_requests_ticket_id'), ['ticket_id'], unique=True)

    op.create_table('surveys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['survey_templates.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surveys_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_audit_log_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_comments_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_kb_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('kb_article_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kb_article_id'], ['kb_articles.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_kb_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_kb_links_kb_article_id'), ['kb_article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_kb_links_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entries_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_user_id'), ['user_id'], unique=False)

    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_responses_survey_id'), ['survey_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError(
        'Tickety migrations are forward-only; restore a verified backup or apply a forward fix.'
    )
    # Historical generated teardown retained below as schema documentation and
    # intentionally unreachable to prevent accidental destructive rollback.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_responses_survey_id'))

    op.drop_table('survey_responses')
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_ticket_id'))

    op.drop_table('time_entries')
    with op.batch_alter_table('ticket_kb_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_kb_links_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_kb_links_kb_article_id'))

    op.drop_table('ticket_kb_links')
    with op.batch_alter_table('ticket_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_comments_ticket_id'))

    op.drop_table('ticket_comments')
    with op.batch_alter_table('ticket_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_audit_log_ticket_id'))

    op.drop_table('ticket_audit_log')
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surveys_ticket_id'))

    op.drop_table('surveys')
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_requests_ticket_id'))

    op.drop_table('service_requests')
    with op.batch_alter_table('recognitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognitions_user_id'))

    op.drop_table('recognitions')
    with op.batch_alter_table('problem_ticket_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_ticket_links_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_problem_ticket_links_problem_id'))

    op.drop_table('problem_ticket_links')
    with op.batch_alter_table('change_ticket_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_ticket_links_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_change_ticket_links_change_id'))

    op.drop_table('change_ticket_links')
    with op.batch_alter_table('change_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_approvals_change_id'))

    op.drop_table('change_approvals')
    with op.batch_alter_table('user_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_mappings_tickety_user_id'))

    op.drop_table('user_mappings')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_external_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    op.drop_table('projects')
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problems_title'))

    op.drop_table('problems')
    with op.batch_alter_table('kb_articles', schema=None) as batch_op:
        batch_op.drop_index('ix_kb_status_cat')
        batch_op.drop_index(batch_op.f('ix_kb_articles_title'))
        batch_op.drop_index(batch_op.f('ix_kb_articles_category'))

    op.drop_table('kb_articles')
    with op.batch_alter_table('changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_changes_title'))

    op.drop_table('changes')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_name'))

    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('ticket_status_config')
    op.drop_table('ticket_priority_config')
    op.drop_table('ticket_categories')
    op.drop_table('sync_state')
    op.drop_table('survey_templates')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('service_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_items_category'))

    op.drop_table('service_items')
    op.drop_table('notification_config')
    # ### end Alembic commands ###
