"""Make AI queue eligibility and dispatch telemetry explicit.

Revision ID: 0019
Revises: 0018
Create Date: 2026-08-25
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0019"
down_revision: Union[str, None] = "0018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("llm_call_records", sa.Column("http_status", sa.Integer(), nullable=True))
    op.add_column("llm_call_records", sa.Column("failure_kind", sa.String(length=64), nullable=True))
    op.add_column("llm_call_records", sa.Column("retry_after_seconds", sa.Integer(), nullable=True))
    op.add_column(
        "llm_call_records",
        sa.Column("dispatched", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "llm_call_records",
        sa.Column("estimated_tokens", sa.Integer(), nullable=False, server_default="0"),
    )

    # These pauses were generated by Tickety's former local estimate ceilings,
    # not by provider Retry-After responses. Background ceilings are now
    # observational, while real provider throttles retain durable cooldowns.
    op.execute("""
        DELETE FROM llm_provider_cooldowns
        WHERE reason IN (
            'provider_capacity',
            'reserved_tokens_day_exhausted',
            'provider_requests_minute_exhausted',
            'provider_tokens_minute_exhausted'
        )
    """)

    # Cancel already queued terminal work without erasing completed artifacts.
    op.execute("""
        UPDATE tickets
        SET ai_status = 'not_applicable',
            ai_claim_id = NULL,
            ai_lease_expires_at = NULL,
            ai_started_at = NULL,
            ai_next_attempt_at = NULL,
            ai_requested_artifacts = NULL,
            ai_attempts = 0,
            ai_error = 'terminal_ticket'
        WHERE LOWER(TRIM(COALESCE(status, ''))) IN (
            SELECT LOWER(name) FROM ticket_status_config WHERE is_terminal = TRUE
            UNION SELECT 'closed'
            UNION SELECT 'resolved'
            UNION SELECT 'cancelled'
        )
          AND ai_status IN (
            'queued', 'running', 'partial', 'stale', 'legacy_stale',
            'provenance_unknown', 'failed', 'dead_letter', 'paused'
          )
    """)


def downgrade() -> None:
    raise RuntimeError(
        "Tickety migrations are forward-only; restore a verified backup or apply a forward fix."
    )
