"use client";

import Link from "next/link";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, Gauge, ListOrdered, Radar, Search, ShieldCheck, Sparkles, Timer, TrendingUp, Users } from "lucide-react";
import { Badge, Button, EmptyState, ErrorState, Skeleton } from "@/components/ui";
import { api } from "@/lib/api";
import type { AccountHealth, SlaStatusItem, SystemicIssuesResponse } from "@/lib/types";
import { cn } from "@/lib/utils";

interface WorkloadAgent { user_id: string; name: string; tier: number; open_tickets: number; total_resolved: number; avg_resolution_hours: number; }
interface WorkloadResponse { agents: WorkloadAgent[]; }

async function getWorkload(): Promise<WorkloadResponse> {
  const response = await fetch("/api/intelligence/workload", { credentials: "include", cache: "no-store" });
  if (!response.ok) throw new Error(`Workload request failed: ${response.status}`);
  return response.json() as Promise<WorkloadResponse>;
}

function Panel({ title, description, icon, children, action, className }: { title: string; description?: string; icon: React.ReactNode; children: React.ReactNode; action?: React.ReactNode; className?: string }) {
  return <section className={cn("overflow-hidden rounded-2xl border border-linen-400 bg-linen-50 shadow-sm", className)}><div className="flex flex-col gap-3 border-b border-linen-400 p-4 sm:flex-row sm:items-start sm:justify-between sm:p-5"><div className="flex min-w-0 gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-linen-200 text-ink-500">{icon}</span><div><h2 className="text-sm font-semibold text-ink-700">{title}</h2>{description && <p className="mt-1 text-xs leading-5 text-ink-500">{description}</p>}</div></div>{action}</div><div className="p-4 sm:p-5">{children}</div></section>;
}

function PanelLoading({ rows = 4 }: { rows?: number }) { return <div className="space-y-3" aria-label="Loading intelligence"><Skeleton className="h-16 w-full" />{Array.from({ length: rows }, (_, index) => <Skeleton key={index} className="h-12 w-full" />)}</div>; }
function PanelError({ title = "Intelligence unavailable", onRetry, retrying }: { title?: string; onRetry: () => void; retrying: boolean }) { return <ErrorState className="min-h-48" title={title} description="This signal could not be refreshed. Other intelligence panels remain independent." onRetry={onRetry} retrying={retrying} />; }
function EmptyPanel({ title, description }: { title: string; description: string }) { return <EmptyState className="min-h-44 border-0 bg-transparent" icon={<ShieldCheck className="h-5 w-5" />} title={title} description={description} />; }

export default function IntelligencePage() {
  return <div className="mx-auto max-w-7xl space-y-6"><header className="grid gap-5 border-b border-linen-400 pb-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-ink-400"><Sparkles className="h-4 w-4" />Decision support</div><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-ink-700">Intelligence</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-ink-500">Explainable operational signals for escalation risk, SLA exposure, prioritization, workload, and systemic issues.</p></div><div className="rounded-xl border border-linen-400 bg-linen-50 px-4 py-3 text-xs leading-5 text-ink-500"><strong className="block text-ink-700">Advisory, not automatic</strong>Recommendations support human decisions and do not change tickets.</div></header><AlertsPanel /><div className="grid gap-6 lg:grid-cols-2"><PriorityPanel /><SlaPanel /></div><div className="grid gap-6 lg:grid-cols-2"><TrendsPanel /><HealthPanel /></div><div className="grid gap-6 lg:grid-cols-2"><WorkloadPanel /><SystemicPanel /></div></div>;
}

function AlertsPanel() {
  const query = useQuery({ queryKey: ["intel-alerts"], queryFn: api.getIntelAlerts, refetchInterval: 30_000 });
  const data = query.data;
  return <Panel title="Proactive alerts" description="Refreshes every 30 seconds · evidence links to source tickets" icon={<AlertTriangle className="h-4 w-4" />} action={data ? <Badge variant={data.summary.sla_breached || data.summary.escalation_prone ? "danger" : "success"} dot>{data.summary.sla_breached || data.summary.escalation_prone ? "Attention needed" : "No critical signals"}</Badge> : undefined}>{query.isLoading ? <PanelLoading rows={2} /> : query.isError ? <PanelError onRetry={() => void query.refetch()} retrying={query.isFetching} /> : !data ? <EmptyPanel title="No alert data" description="The intelligence service returned no alert summary." /> : <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Signal label="Escalation prone" value={data.summary.escalation_prone} tone="danger" /><Signal label="SLA at risk" value={data.summary.sla_at_risk} tone="warning" /><Signal label="SLA breached" value={data.summary.sla_breached} tone="danger" /></div>{data.escalation_prone.length > 0 && <div><h3 className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-400">Highest escalation risk</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{data.escalation_prone.slice(0, 6).map((item) => <Link key={item.ticket_id} href={`/tickets/${item.ticket_id}`} className="rounded-xl border border-rust-400/30 bg-[var(--color-danger-soft)] p-4 transition-colors hover:border-rust-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]"><div className="flex items-start justify-between gap-3"><p className="line-clamp-2 text-sm font-semibold text-ink-700">{item.subject}</p><Badge variant="danger">{item.priority}</Badge></div><RiskMeter value={item.risk} /></Link>)}</div></div>}{data.sla_breached.length > 0 && <div><h3 className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-400">Breached SLA clocks</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{data.sla_breached.slice(0, 4).map((item) => <SlaItem key={item.ticket_id} item={item} />)}</div></div>}{data.summary.escalation_prone === 0 && data.summary.sla_at_risk === 0 && data.summary.sla_breached === 0 && <EmptyPanel title="No active exceptions" description="Current signals show no escalation or SLA intervention requirement." />}</div>}</Panel>;
}

function Signal({ label, value, tone }: { label: string; value: number; tone: "danger" | "warning" }) { return <div className="rounded-xl border border-linen-400 bg-linen-100 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-medium text-ink-500">{label}</p><Badge variant={tone}>{value > 0 ? "Review" : "Clear"}</Badge></div><p className="mt-3 text-3xl font-semibold tracking-[-0.04em] tabular-nums text-ink-700">{value}</p></div>; }
function RiskMeter({ value }: { value: number }) { const normalized = Math.max(0, Math.min(value, 100)); return <div className="mt-4"><div className="mb-1.5 flex items-center justify-between text-xs"><span className="text-ink-500">Risk score</span><strong className="tabular-nums text-ink-700">{normalized}/100</strong></div><div className="h-2 overflow-hidden rounded-full bg-white/70" role="progressbar" aria-label="Escalation risk" aria-valuenow={normalized} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-semantic-danger" style={{ width: `${normalized}%` }} /></div></div>; }

function PriorityPanel() {
  const query = useQuery({ queryKey: ["intel-prioritize"], queryFn: api.getIntelPrioritize }); const ranked = query.data?.ranked ?? [];
  return <Panel title="Backlog priority" description="Ranked by declared priority, age, sentiment, and escalation exposure" icon={<ListOrdered className="h-4 w-4" />}>{query.isLoading ? <PanelLoading /> : query.isError ? <PanelError onRetry={() => void query.refetch()} retrying={query.isFetching} /> : ranked.length === 0 ? <EmptyPanel title="Backlog is clear" description="No open tickets are currently available for ranking." /> : <ol className="space-y-2">{ranked.slice(0, 8).map((item, index) => <li key={item.ticket_id}><Link href={`/tickets/${item.ticket_id}`} className="grid grid-cols-[2rem_minmax(0,1fr)_auto] items-center gap-3 rounded-xl border border-linen-300 p-3 transition-colors hover:border-linen-500 hover:bg-linen-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-ink-700 text-xs font-semibold text-white">{index + 1}</span><span className="min-w-0"><span className="block truncate text-sm font-semibold text-ink-700">{item.subject}</span><span className="mt-1 block truncate text-xs text-ink-500">{item.priority} · {item.category || "Uncategorized"} · {Math.round(item.age_hours)}h old · risk {Math.round(item.escalation_risk)}</span></span><span className="text-right"><strong className="block text-sm tabular-nums text-ink-700">{item.score}</strong><span className="text-[10px] uppercase tracking-wide text-ink-400">score</span></span></Link></li>)}</ol>}</Panel>;
}

function SlaPanel() {
  const query = useQuery({ queryKey: ["intel-sla"], queryFn: api.getIntelSla }); const items = query.data?.items ?? [];
  return <Panel title="SLA clocks" description="Remaining time and target exposure for open work" icon={<Timer className="h-4 w-4" />}>{query.isLoading ? <PanelLoading /> : query.isError ? <PanelError onRetry={() => void query.refetch()} retrying={query.isFetching} /> : items.length === 0 ? <EmptyPanel title="No active SLA clocks" description="No open tickets are currently being tracked." /> : <div className="space-y-2">{items.slice(0, 10).map((item) => <SlaItem key={item.ticket_id} item={item} />)}</div>}</Panel>;
}

function SlaItem({ item }: { item: SlaStatusItem }) { const variant = item.status === "breached" ? "danger" : item.status === "at_risk" ? "warning" : "success"; return <Link href={`/tickets/${item.ticket_id}`} className="flex items-center gap-3 rounded-xl border border-linen-300 p-3 transition-colors hover:bg-linen-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)]"><Badge variant={variant} dot>{item.status.replace("_", " ")}</Badge><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-ink-700">{item.subject}</span><span className="mt-0.5 block text-xs text-ink-500">{item.priority} · {item.sla_target_hours}h target</span></span><span className="shrink-0 text-right text-xs"><strong className="block tabular-nums text-ink-700">{item.status === "breached" ? `${item.elapsed_hours}h elapsed` : `${item.remaining_hours}h left`}</strong></span></Link>; }

function TrendsPanel() {
  const query = useQuery({ queryKey: ["intel-trends"], queryFn: api.getIntelTrends }); const data = query.data; const maxCategory = data ? Math.max(1, ...Object.values(data.by_category)) : 1;
  return <Panel title="Trends and text signals" description="Category, sentiment, and recurring language across ticket history" icon={<TrendingUp className="h-4 w-4" />}>{query.isLoading ? <PanelLoading /> : query.isError ? <PanelError onRetry={() => void query.refetch()} retrying={query.isFetching} /> : !data || data.total_tickets === 0 ? <EmptyPanel title="No trend history yet" description="Signals will appear when enough ticket activity has accumulated." /> : <div className="space-y-6"><div><h3 className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-400">Category volume</h3><div className="mt-3 space-y-3">{Object.entries(data.by_category).slice(0, 8).map(([category, count]) => <div key={category} className="grid grid-cols-[6rem_1fr_2rem] items-center gap-3 text-xs"><span className="truncate text-ink-600">{category}</span><div className="h-2 overflow-hidden rounded-full bg-linen-300"><div className="h-full rounded-full bg-semantic-primary" style={{ width: `${(count / maxCategory) * 100}%` }} /></div><span className="text-right tabular-nums text-ink-500">{count}</span></div>)}</div></div><div className="grid gap-5 sm:grid-cols-2"><div><h3 className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-400">Sentiment</h3><div className="mt-3 flex flex-wrap gap-2">{Object.entries(data.by_sentiment).map(([sentiment, count]) => <Badge key={sentiment} variant={sentiment.toLowerCase().includes("negative") ? "danger" : sentiment.toLowerCase().includes("positive") ? "success" : "neutral"}>{sentiment}: {count}</Badge>)}</div></div><div><h3 className="text-xs font-semibold uppercase tracking-[0.1em] text-ink-400">Top terms</h3><div className="mt-3 flex flex-wrap gap-2">{data.top_terms.slice(0, 14).map(([term, count]) => <Badge key={term}>{term} · {count}</Badge>)}</div></div></div></div>}</Panel>;
}

function HealthPanel() {
  const [reporter, setReporter] = useState(""); const [activeReporter, setActiveReporter] = useState("");
  const query = useQuery<AccountHealth>({ queryKey: ["intel-health", activeReporter], queryFn: () => api.getIntelHealth(activeReporter), enabled: Boolean(activeReporter) });
  const submit = (event: React.FormEvent) => { event.preventDefault(); const value = reporter.trim(); if (value) setActiveReporter(value); };
  const search = <form onSubmit={submit} className="flex w-full gap-2 sm:w-auto"><label className="relative min-w-0 flex-1 sm:w-52"><span className="sr-only">Reporter or customer</span><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ink-400" /><input className="input-base input-search h-10 w-full" value={reporter} onChange={(event) => setReporter(event.target.value)} placeholder="Reporter or customer" /></label><Button type="submit" size="sm" disabled={!reporter.trim()}>Check</Button></form>;
  const data = query.data;
  return <Panel title="Account health" description="Search a reporter to summarize their ticket history and churn signal" icon={<Gauge className="h-4 w-4" />} action={search}>{!activeReporter ? <EmptyPanel title="Choose an account" description="Enter a reporter or customer identifier to calculate a health score." /> : query.isLoading ? <PanelLoading rows={2} /> : query.isError ? <PanelError title="Account health unavailable" onRetry={() => void query.refetch()} retrying={query.isFetching} /> : !data || data.health_score == null ? <EmptyPanel title={`No history for “${activeReporter}”`} description="Try the reporter name or identifier recorded on their tickets." /> : <div className="space-y-5"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="grid h-24 w-24 shrink-0 place-items-center rounded-full border-[10px] border-linen-300"><span className="text-2xl font-semibold tabular-nums text-ink-700">{data.health_score}</span></div><div><Badge variant={data.churn_risk === "high" ? "danger" : data.churn_risk === "medium" ? "warning" : "success"} dot>{data.churn_risk} churn risk</Badge><p className="mt-3 text-sm text-ink-600">{data.open} open · {data.resolved} resolved · {data.total} total tickets</p><p className="mt-1 text-xs text-ink-500">Average escalation risk {data.avg_escalation_risk} · negative sentiment {(data.negative_sentiment_ratio * 100).toFixed(0)}%</p></div></div><div className="rounded-xl border border-linen-400 bg-linen-100 p-4 text-xs leading-5 text-ink-500"><strong className="block text-ink-700">Routing remains ticket-specific</strong>Open a ticket to review the recommended assignee and its supporting factors.</div></div>}</Panel>;
}

function WorkloadPanel() {
  const query = useQuery({ queryKey: ["agent-workload"], queryFn: getWorkload }); const agents = query.data?.agents ?? [];
  return <Panel title="Agent workload" description="Open assignment load and historical delivery by agent" icon={<Users className="h-4 w-4" />}>{query.isLoading ? <PanelLoading /> : query.isError ? <PanelError title="Workload unavailable" onRetry={() => void query.refetch()} retrying={query.isFetching} /> : agents.length === 0 ? <EmptyPanel title="No active assignments" description="No agents currently have assigned tickets." /> : <div className="space-y-2">{agents.slice(0, 8).map((agent) => <div key={agent.user_id} className="rounded-xl border border-linen-300 p-3"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-ink-700">{agent.name}</p><p className="mt-0.5 text-xs text-ink-400">Tier {agent.tier}</p></div><Badge variant={agent.open_tickets > 8 ? "warning" : "info"}>{agent.open_tickets} open</Badge></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-ink-500"><span>{agent.total_resolved} resolved</span>{agent.avg_resolution_hours > 0 && <span>{agent.avg_resolution_hours}h average resolution</span>}</div></div>)}</div>}</Panel>;
}

function SystemicPanel() {
  const query = useQuery<SystemicIssuesResponse>({ queryKey: ["intel-systemic"], queryFn: () => api.getIntelSystemic(2) }); const data = query.data;
  return <Panel title="Systemic issues" description="Clusters of related tickets that may share a root cause" icon={<Radar className="h-4 w-4" />}>{query.isLoading ? <PanelLoading /> : query.isError ? <PanelError title="Systemic analysis unavailable" onRetry={() => void query.refetch()} retrying={query.isFetching} /> : !data || data.clusters.length === 0 ? <EmptyPanel title="No systemic clusters detected" description={`${data?.total_tickets ?? 0} tickets analysed; current issues appear isolated.`} /> : <div className="space-y-3"><p className="text-xs leading-5 text-ink-500">{data.clusters.length} cluster{data.clusters.length === 1 ? "" : "s"} cover {data.clustered_tickets} of {data.total_tickets} analysed tickets.</p>{data.clusters.map((cluster) => <article key={cluster.cluster_id} className="rounded-xl border border-linen-400 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><h3 className="text-sm font-semibold text-ink-700">{cluster.cluster_id}</h3><div className="flex flex-wrap gap-2"><Badge variant="info">{cluster.ticket_count} tickets</Badge><Badge variant={cluster.business_impact_score >= 70 ? "danger" : "warning"}>Impact {cluster.business_impact_score}</Badge></div></div><div className="mt-3 flex flex-wrap gap-1.5">{cluster.shared_keywords.slice(0, 8).map((keyword) => <Badge key={keyword}>{keyword}</Badge>)}</div><ul className="mt-3 space-y-1">{cluster.samples.map((sample, index) => <li key={`${cluster.cluster_id}-${index}`} className="truncate text-xs text-ink-500">{sample}</li>)}</ul></article>)}</div>}</Panel>;
}
